refactor

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,12 +7,6 @@ on:
   workflow_dispatch:
 
 env:
-  BYOND_VERSION: ""
-  BYOND_MAJOR_VERSION: ""
-  BYOND_MINOR_VERSION: ""
-  BYOND_BETA_VERSION: ""
-  BYOND_BETA_MAJOR_VERSION: ""
-  BYOND_BETA_MINOR_VERSION: ""
   REGISTRY: ghcr.io
 
 jobs:
@@ -22,69 +16,60 @@ jobs:
     steps:
       - name: Checkout the repository
         uses: actions/checkout@v3
-
-      - name: Check for the latest stable version of BYOND
-        run: |
-          BYOND_VERSION="$(sed -n 1p <(curl https://secure.byond.com/download/version.txt))"
-          BYOND_MAJOR_VERSION="$(echo "$(cut -d '.' -f 1 <(echo "$BYOND_VERSION"))")"
-          BYOND_MINOR_VERSION="$(echo "$(cut -d '.' -f 2 <(echo "$BYOND_VERSION"))")"
-          echo "BYOND_VERSION="$BYOND_VERSION"" >> $GITHUB_ENV
-          echo "BYOND_MAJOR_VERSION="$BYOND_MAJOR_VERSION"" >> $GITHUB_ENV
-          echo "BYOND_MINOR_VERSION="$BYOND_MINOR_VERSION"" >> $GITHUB_ENV
       
-      - name: Check for stable linux release binaries
-        id: binaries_stable_release_check
-        continue-on-error: true
-        run: |
-          RESPONSE=$(curl --head --silent "http://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" | head -n1 | cut -d ' ' -f 2)
-          RESPONSE=$(($RESPONSE))
-
-          if [ $RESPONSE -ne 200 ]; then
-            exit $RESPONSE
-          fi
-
-      - name: Check for the latest beta version of BYOND
-        run: |
-          BYOND_BETA_VERSION="$(sed -n 2p <(curl https://secure.byond.com/download/version.txt))"
-          BYOND_BETA_MAJOR_VERSION="$(echo "$(cut -d '.' -f 1 <(echo "$BYOND_BETA_VERSION"))")"
-          BYOND_BETA_MINOR_VERSION="$(echo "$(cut -d '.' -f 2 <(echo "$BYOND_BETA_VERSION"))")"
-          echo "BYOND_BETA_VERSION="$BYOND_BETA_VERSION"" >> $GITHUB_ENV
-          echo "BYOND_BETA_MAJOR_VERSION="$BYOND_BETA_MAJOR_VERSION"" >> $GITHUB_ENV
-          echo "BYOND_BETA_MINOR_VERSION="$BYOND_BETA_MINOR_VERSION"" >> $GITHUB_ENV
-      
-      - name: Check for beta linux release binaries
-        id: binaries_beta_release_check
-        continue-on-error: true
-        run: |
-          RESPONSE=$(curl --head --silent "http://www.byond.com/download/build/${BYOND_BETA_MAJOR_VERSION}/${BYOND_BETA_MAJOR_VERSION}.${BYOND_BETA_MINOR_VERSION}_byond_linux.zip" | head -n1 | cut -d ' ' -f 2)
-          RESPONSE=$(($RESPONSE))
-
-          if [ $RESPONSE -ne 200 ]; then
-            exit $RESPONSE
-          fi
-
       - name: Login to the Docker Registry
         uses: docker/login-action@v2
         with:
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Check for the latest stable version of BYOND
+        id: stable-version-check
+        run: |
+          BYOND_VERSION="$(sed -n 1p <(curl https://secure.byond.com/download/version.txt))"
+          BYOND_MAJOR_VERSION="$(echo "$(cut -d '.' -f 1 <(echo "$BYOND_VERSION"))")"
+          BYOND_MINOR_VERSION="$(echo "$(cut -d '.' -f 2 <(echo "$BYOND_VERSION"))")"
+          echo "BYOND_VERSION="$BYOND_VERSION"" >> $GITHUB_OUTPUT
+          echo "BYOND_MAJOR_VERSION="$BYOND_MAJOR_VERSION"" >> $GITHUB_OUTPUT
+          echo "BYOND_MINOR_VERSION="$BYOND_MINOR_VERSION"" >> $GITHUB_OUTPUT
+          echo "✔️ The latest stable version of BYOND: ${BYOND_VERSION}"
+      
+      - name: Check for stable linux release binaries
+        id: binaries_stable_release_check
+        continue-on-error: true
+        env:
+          BYOND_VERSION: ${{ steps.stable-version-check.outputs.BYOND_VERSION }}
+          BYOND_MAJOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MAJOR_VERSION }}
+          BYOND_MINOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MINOR_VERSION }}
+        run: |
+          RESPONSE=$(curl --head --silent "http://www.byond.com/download/build/${BYOND_MAJOR_VERSION}/${BYOND_MAJOR_VERSION}.${BYOND_MINOR_VERSION}_byond_linux.zip" | head -n1 | cut -d ' ' -f 2)
+          RESPONSE=$(($RESPONSE))
+
+          if [ $RESPONSE -eq 200 ]; then
+            echo "✅ Beta linux release binaries were found for BYOND version: ${BYOND_VERSION}"
+          else
+            echo "❌ Beta linux release binaries could not be found for BYOND version: ${BYOND_VERSION}"
+            exit $RESPONSE
+          fi
       
       - name: Check if the stable release was already published to the Docker Registry
         id: docker_stable_release_check
         continue-on-error: true
+        env:
+          BYOND_VERSION: ${{ steps.stable-version-check.outputs.BYOND_VERSION }}
+          BYOND_MAJOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MAJOR_VERSION }}
+          BYOND_MINOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MINOR_VERSION }}
         run: |
-          docker manifest inspect ${{ env.REGISTRY }}/neurekadev/byond:${{ env.BYOND_VERSION }}
-      
-      - name: Check if the beta release was already published to the Docker Registry
-        id: docker_beta_release_check
-        continue-on-error: true
-        run: |
-          docker manifest inspect ${{ env.REGISTRY }}/neurekadev/byond:${{ env.BYOND_BETA_VERSION }}-beta
+          docker manifest inspect ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_VERSION }}
       
       - name: Build the stable Docker image and publish to the Docker Registry
         uses: docker/build-push-action@v4
         if: ${{ steps.binaries_stable_release_check.outcome == 'success' && steps.docker_stable_release_check.outcome == 'failure' }}
+        env:
+          BYOND_VERSION: ${{ steps.stable-version-check.outputs.BYOND_VERSION }}
+          BYOND_MAJOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MAJOR_VERSION }}
+          BYOND_MINOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MINOR_VERSION }}
         with:
           context: .
           push: true
@@ -95,17 +80,60 @@ jobs:
             ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_VERSION }}
             ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_MAJOR_VERSION }}
             ${{ env.REGISTRY }}/${{ github.repository }}:latest
+
+      - name: Check for the latest beta version of BYOND
+        id: beta-version-check
+        run: |
+          BYOND_VERSION="$(sed -n 2p <(curl https://secure.byond.com/download/version.txt))"
+          BYOND_MAJOR_VERSION="$(echo "$(cut -d '.' -f 1 <(echo "$BYOND_VERSION"))")"
+          BYOND_MINOR_VERSION="$(echo "$(cut -d '.' -f 2 <(echo "$BYOND_VERSION"))")"
+          echo "BYOND_VERSION="$BYOND_VERSION"" >> $GITHUB_OUTPUT
+          echo "BYOND_MAJOR_VERSION="$BYOND_MAJOR_VERSION"" >> $GITHUB_OUTPUT
+          echo "BYOND_MINOR_VERSION="$BYOND_MINOR_VERSION"" >> $GITHUB_OUTPUT
+          echo "✔️ The latest beta version of BYOND: ${BYOND_VERSION}"
+      
+      - name: Check for beta linux release binaries
+        id: binaries_beta_release_check
+        continue-on-error: true
+        env:
+          BYOND_VERSION: ${{ steps.beta-version-check.outputs.BYOND_VERSION }}
+          BYOND_MAJOR_VERSION: ${{ steps.beta-version-check.outputs.BYOND_MAJOR_VERSION }}
+          BYOND_MINOR_VERSION: ${{ steps.beta-version-check.outputs.BYOND_MINOR_VERSION }}
+        run: |
+          RESPONSE=$(curl --head --silent "http://www.byond.com/download/build/${BYOND_MAJOR_VERSION}/${BYOND_MAJOR_VERSION}.${BYOND_MINOR_VERSION}_byond_linux.zip" | head -n1 | cut -d ' ' -f 2)
+          RESPONSE=$(($RESPONSE))
+
+          if [ $RESPONSE -eq 200 ]; then
+            echo "✅ Beta linux release binaries were found for BYOND version: ${BYOND_VERSION}"
+          else
+            echo "❌ Beta linux release binaries could not be found for BYOND version: ${BYOND_VERSION}"
+            exit $RESPONSE
+          fi
+      
+      - name: Check if the beta release was already published to the Docker Registry
+        id: docker_beta_release_check
+        continue-on-error: true
+        env:
+          BYOND_VERSION: ${{ steps.beta-version-check.outputs.BYOND_VERSION }}
+          BYOND_MAJOR_VERSION: ${{ steps.beta-version-check.outputs.BYOND_MAJOR_VERSION }}
+          BYOND_MINOR_VERSION: ${{ steps.beta-version-check.outputs.BYOND_MINOR_VERSION }}
+        run: |
+          docker manifest inspect ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_VERSION }}-beta
       
       - name: Build the beta Docker image and publish to the Docker Registry
         uses: docker/build-push-action@v4
         if: ${{ steps.binaries_beta_release_check.outcome == 'success' && steps.docker_beta_release_check.outcome == 'failure' }}
+        env:
+          BYOND_VERSION: ${{ steps.beta-version-check.outputs.BYOND_VERSION }}
+          BYOND_MAJOR_VERSION: ${{ steps.beta-version-check.outputs.BYOND_MAJOR_VERSION }}
+          BYOND_MINOR_VERSION: ${{ steps.beta-version-check.outputs.BYOND_MINOR_VERSION }}
         with:
           context: .
           push: true
           build-args: |
-            BYOND_MAJOR=${{ env.BYOND_BETA_MAJOR_VERSION }}
-            BYOND_MINOR=${{ env.BYOND_BETA_MINOR_VERSION }}
+            BYOND_MAJOR=${{ env.BYOND_MAJOR_VERSION }}
+            BYOND_MINOR=${{ env.BYOND_MINOR_VERSION }}
           tags: |
-            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_BETA_VERSION }}-beta
-            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_BETA_MAJOR_VERSION }}-beta
+            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_VERSION }}-beta
+            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_MAJOR_VERSION }}-beta
             ${{ env.REGISTRY }}/${{ github.repository }}:beta
